services:
  01_backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/backend
    environment:
      - DB_HOST=data_base
      - DB_NAME=LH_base
      - DB_USER=admin
      - DB_PASS=root
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - data_base


  01_frontend:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "5173:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - NODE_ENV=development
    command: npm run dev
    depends_on:
      - 01_backend
  

  data_base:
    image: postgres:14.6-alpine
    ports:
      - "5432:5432"
    container_name: LH_DB
    environment:
      - POSTGRES_DB=LH_base
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=root

    



  # db_auth:
  #   container_name: data_base
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_PASSWORD=root
  #     - POSTGRES_USER=admin
  #   image: postgres:15-alpine

  